env:
  global:
    - secure: OkkwXgHsaQgQ9D6DvliUharlbmvd8UtN0m62E2uXOw3rursTqPcnNdeTmFk0nty/NHdUlZW7tYlLjhwY070B0z1rfXHdIChgQtiOZkltPjS+dXXT24cU8JnYSZJ8nSJ9aeiJcf+prS2zFm/7TiXYpzkniaBglp2FpR4u8Gt9M9WhC7lojZ5cQUac5ay2YhB/+bARb3rTWnuk+bPR5YNbKPMD64nAn+srREWO9cb+Q7lXVfFFUDTdbvuVpwwxwzuQOmYsmESz9PszP7Bp4M33C+J4egnWUoqmRBIfX0D88HHgFjP1dy7zlI1+Oh9x2LLa4rS9+jc/clB60LBFmoWgf6HTbS0mWwR1g1fRVnoAk/AGgIsf2mJmMwzJkdUlfF2B/PWvgmx00iFPsyt9uappb/Z531aT1cyCTuBhyVPFQc2LWwNMGytsk6jyGVH7ka3YB9EUHHQrrZ4WfYBHSvk/4HyVZ87Chy/6baZEh2WMM/owCW8oSBq6yMIaoKa5CQH/7LwZ7JjnbmcirnlBqlmboSm7Qn/8omU/nnYlm3K7WSa1u0CcDmtWcxiC4KMb7XAukT7HwE0qodege1fmjdiOFcnWV5UlbzjJNi+BGDj8vawFh5hpeQ+8KMD09Mlxs2wJ0m8oSqGXqV6hJ7pdjunLjPXAm/rny+bMEpeD4FX0ZFY=
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build -v
matrix:
  allow_failure:
    - rust: nightly
after_success: |
  http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
