language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build -v
  - cargo doc -v
matrix:
  allow_failure:
    - rust: nightly
after_success:
  - curl https://ticki.github.io/Open-Sea/docupload.sh | sh
